[workspace]
members = [
  "gpu-back",
  "gpu-client",
  "gpu-common",
  "gpu-compiler",
  "gpu-wasm-client",
  "gpu-wasm-compiler",
  "gpu-log",
  "gpu-tauri",
]
resolver = "2"

[patch.crates-io]
naga = { git = "https://github.com/gputoy/naga.git" }
