# ----------------- Basic tasks -------------------
[tasks.fmt]
command = "cargo"
args = ["fmt", "--all"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.clean]
clear = true
workspace = false
description = "Cleans wasm build package"
script = """
  rm -rf ./front/pkg
"""

[tasks.deep-clean]
workspace = false
description = "Cleans all build artifacts"
script = "rm -rf ./dist ./target ./front/pkg"

# ----------------- Wasm build -------------------
[tasks.wasm-client-dev]
workspace = false
condition = { profiles = ["development"] }
description = "Generate wasm client"
script = """\
  RUSTFLAGS=--cfg=web_sys_unstable_apis \
  wasm-pack build ./gpu-wasm-client --out-dir ../front/pkg/client  --target web --mode no-install --dev
"""

[tasks.wasm-client-prod]
workspace = false
condition = { profiles = ["production"] }
description = "Generate wasm client (release)"
script = """\
  RUSTFLAGS=--cfg=web_sys_unstable_apis \
  wasm-pack build gpu-wasm-client --out-dir ../front/pkg/client  --target web --mode no-install &&\
  echo "gpu-client size pre-optimize: $(wc -c < front/pkg/client/gpu_wasm_client_bg.wasm)B"
  wasm-opt -Os -o front/pkg/client/gpu_wasm_client_bg.wasm front/pkg/client/gpu_wasm_client_bg.wasm 
  echo "gpu-client size post-optimize: $(wc -c < front/pkg/client/gpu_wasm_client_bg.wasm)B"
"""

[tasks.wasm-compiler-dev]
workspace = false
condition = { profiles = ["development"] }
description = "Generate wasm compiler"
script = """\
  RUSTFLAGS=--cfg=web_sys_unstable_apis \
  wasm-pack build ./gpu-wasm-compiler --out-dir ../front/pkg/compiler  --target web --mode no-install --dev
"""

[tasks.wasm-compiler-prod]
workspace = false
condition = { profiles = ["production"] }
description = "Generate wasm compiler (release)"
script = """\
  RUSTFLAGS=--cfg=web_sys_unstable_apis \
  wasm-pack build gpu-wasm-compiler --out-dir ../front/pkg/compiler  --target web --mode no-install &&\
  echo "gpu-compiler size pre-optimize: $(wc -c < front/pkg/compiler/gpu_wasm_compiler_bg.wasm)B"
  wasm-opt -Os -o front/pkg/compiler/gpu_wasm_compiler_bg.wasm front/pkg/compiler/gpu_wasm_compiler_bg.wasm 
  echo "gpu-compiler size post-optimize: $(wc -c < front/pkg/compiler/gpu_wasm_compiler_bg.wasm)B"
"""

[tasks.wasm]
description = "Building .wasm packages outputting compiled module to front/pgk"
workspace = false
clear = true
dependencies = [
  "clean",
  "wasm-client-dev",
  "wasm-client-prod",
  "wasm-compiler-dev",
  "wasm-compiler-prod",
]

# ------------------- Api ---------------------
[tasks.api-dev]
condition = { profiles = ["development"] }
description = "Serve backend"
workspace = false
script = """
  RUST_LOG=info cargo run --package gpu-back
"""

[tasks.api-prod]
condition = { profiles = ["production"] }
description = "Serve backend"
workspace = false
script = """
  RUST_LOG=log cargo run --package gpu-back --release
"""

# ----------------- Front    -------------------
[tasks.front-dev]
condition = { profiles = ["development"] }
description = "Building and running sveltekit server"
workspace = false
script = ["cd front", "npm run dev -- --port 3000"]

[tasks.front-prod]
condition = { profiles = ["production"] }
workspace = false
script = ["cd front", "npm run build", "node ../dist/index.js"]

[tasks.front]
description = "Building .wasm from gpu-wasm and outputting compiled module to front/pgk"
workspace = false
dependencies = ["front-dev", "front-prod"]


# ----------------- Runners -------------------
[tasks.start]
description = "Building and running sveltekit server"
workspace = false
dependencies = ["wasm", "front"]

[tasks.api]
description = "Building api from gpu-back"
workspace = false
dependencies = ["migrate", "api-dev", "api-prod"]

# ----------------- Database -----------------
[tasks.migrate]
description = "Migrate database with sqlx"
workspace = false
command = "sqlx"
args = ["migrate", "run"]


# ----------------- Types -----------------
[tasks.types]
description = "Make json schema and typescript types from rust types"
workspace = false
script = [
  "cargo run -p gpu-common",
  "cd front",
  "node generate_common_types.js",
]

# ----------------- Env -------------------
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
