[phases.setup]
nixPkgs = ['rustup', 'openssl', 'cmake']

[phases.install]
cmds = ['rustup default stable']
aptPkgs = ['libssl-dev', 'build-essential']

[phases.build]
cmds = ['make api-build target=prod']
dependsOn = ['install']

[start]
cmd = 'make api target=prod'
