[phases.setup]
nixPkgs = ['rustup', 'openssl', 'cmake']

[phases.install]
cmds = ['rustup default stable']
aptPkgs = ['libssl-dev', 'build-essential']

[phases.build]
cmds = ['cargo build --package gpu-back --release']
dependsOn = ['install']

[start]
cmd = './target/release/gpu-back'
