[phases.setup]
nixPkgs = ['nodejs', 'rustup', 'wasm-pack', 'wasm-bindgen-cli', 'openssl']

[phases.install]
cmds = ['rustup default stable']
aptPkgs = ['libssl-dev', 'binaryen', 'build-essential']

[phases.build]
cmds = ["make front-build target=prod"]
dependsOn = ['install']

[start]
cmd = 'make start target=prod'
