[phases.setup]
nixPkgs = ['nodejs', 'rustup', 'wasm-pack', 'wasm-bindgen-cli', 'openssl']


[phases.install]
cmds = ['rustup default stable']
aptPkgs = ['pkg-config', 'libssl-dev', 'build-essential', 'tree']

[phases.build]
cmds = ["""\
  RUSTFLAGS=--cfg=web_sys_unstable_apis \
  wasm-pack build ./gpu-wasm/ --out-dir ../front/pkg \
  --target web --mode no-install --release\
  """, 'cd front && npm install', 'tree -fiL 2 && cd front && npm run build']
dependsOn = ['install']

[start]
cmd = 'node dist/index.js'
