[phases.setup]
nixPkgs = ['nodejs', 'rustup', 'wasm-pack', 'wasm-bindgen-cli', 'openssl']

[phases.install]
cmds = ['rustup default stable']
aptPkgs = ['pkg-config', 'libssl-dev', 'build-essential', 'tree', 'binaryen']

[phases.build]
cmds = [
  """\
  RUSTFLAGS=--cfg=web_sys_unstable_apis \
  wasm-pack build ./gpu-wasm-client/ --out-dir ../front/pkg/client \
  --target web --release
  """,
  'wasm-opt -Os -o front/pkg/client/gpu_wasm_client_bg.wasm front/pkg/gpu_wasm_client_bg.wasm',
  """\
  wasm-pack build ./gpu-wasm-compiler/ --out-dir ../front/pkg/compiler \
  --target web --release
  """,
  'wasm-opt -Os -o front/pkg/compiler/gpu_wasm_compiler_bg.wasm front/pkg/gpu_wasm_compiler_bg.wasm',
  'cd front && npm install',
  'cd front && npm run build',
]
dependsOn = ['install']

[start]
cmd = 'node dist/index.js'
